### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WeissL0** [Celarye/paperback-themes#11]
**Describe the bug:**

**To Reproduce:**
Steps to reproduce the behavior.

**Expected behavior:**

**Additional information:**
 - IOS: [e.g. iOS 8.1]
 - App version [e.g. 0.7 r45]

**Screenshot(s)/ screen recording(s):**

**Additional context:**

**Comment by Celarye** [comment]
Please don’t open an empty issue.
