### ISSUE TITLE
[REQUEST] Sakura theme

### ISSUE THREAD

**Issue by roller0** [Celarye/Paperback-themes#4]
maybe a Sakura theme? with either the outside color being white and the font being pink or the font being white and the outside color being pink, no image of reference but o think the colors would be easy to replicate into a theme perhaps.

**Comment by Celarye** [comment]
I suppose you're refering to Sakura Haruno from Naruto?

**Comment by Celarye** [comment]
The Sakura theme has been created (together with the extra Moonlight Blue theme that you requested) and will be released in a bit.
