### ISSUE TITLE
Black and White theme

### ISSUE THREAD

**Issue by roller0** [Celarye/Paperback-themes#5]
**The theme you would like to be added:**
Perhaps a manga theme style? Like this,basically black lettering and a white outside maybe?
**A possible example:**
![BB24A240-A3FE-43AD-9EDC-7E07C22B61FF](https://user-images.githubusercontent.com/115336040/195371157-629adfb4-7ec2-4e6e-883c-1a3af76becc3.png)

**Additional context:**

**Comment by Celarye** [comment]
@roller0 does this theme fit the bill?https://github.com/Celarye/Paperback-themes/tree/master/Themes/Spot/BlackAndWhite

**Comment by Celarye** [comment]
Clossing this as completed for now, you can reopen this issue in case the recommended theme didn't match your requirements.
